GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/2/ HTTP/1.1
#For the "RetrieveUpdateDestroyAPIView"

###

DELETE http://localhost:8000/products/2/ HTTP/1.1
#For the "RetrieveUpdateDestroyAPIView"
#Because of the "get_permissions()" method it doesn't work if not admin.
#You may get the access token via "POST http://localhost:8000/api/token/" below.

###

PUT http://localhost:8000/products/2/ HTTP/1.1
#Also for the "RetrieveUpdateDestroyAPIView"
#Because of the "get_permissions()" method it doesn't work if not admin.
#You may get the access token via "POST http://localhost:8000/api/token/" below.

Content-Type: application/json

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

#We need to be an admin user to send the 'POST' request.
POST http://localhost:8000/products/ HTTP/1.1
#For "ProductListCreateAPIView"
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5NDQ5NTU3LCJpYXQiOjE3Njk0NDkyNTcsImp0aSI6IjE3MWUwZTIyM2QzNTRiZTlhZWJiZDg1ZTMyZGQ0ZTYxIiwidXNlcl9pZCI6IjEifQ.cQEVAq9mfqr5uY13pHy-aYKeokEG97V7JXbNKJVxgQ8
#Authorization header token was obtained from the admin registration below.
#If you change the "username"/"password" to someone who is not an admin and get it's token, to the bearer,
#It won't work because of the "get_permissions()" method of "ProductListCreateAPIView"
#Bearer tokens can expire in 15 minutes and you may get 401

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "john-doe",
    "password": "123698745j"
}

###

GET http://localhost:8000/user-orders/ HTTP/1.1
#For "UserOrderListAPIView"
#If we don't use "Authorization"; we get "HTTP/1.1 401 Unauthorized"
#Because UserOrderListAPIView's permission_classes = [IsAuthenticated]
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5NDQ5NTU3LCJpYXQiOjE3Njk0NDkyNTcsImp0aSI6IjE3MWUwZTIyM2QzNTRiZTlhZWJiZDg1ZTMyZGQ0ZTYxIiwidXNlcl9pZCI6IjEifQ.cQEVAq9mfqr5uY13pHy-aYKeokEG97V7JXbNKJVxgQ8

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json
#Refresh token

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2OTYyMTMzNywiaWF0IjoxNzY5NTM0OTM3LCJqdGkiOiJlZDJjNTlmMWUzYWU0MjA3OWE0YmVhMmJmYjJhZTRlZCIsInVzZXJfaWQiOiIxIn0.SMDx0ZAA3b8dliuc3bfxCr_c2ZUMGU6vYe_aB8JEVFw"
}

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMjYxNzc3LCJpYXQiOjE3NzEyNjE0NzcsImp0aSI6IjVhZjA0OTY3NWI4ODRmOWFiMGEwZDI5NmU0YTM2OGZiIiwidXNlcl9pZCI6IjIifQ.zAAcu5XwV3-04GwOnHroYUZle6lZH-EjrH_kG8lXsr0

###

GET http://localhost:8000/orders/4fa3bb60-982a-421f-8c8c-11cf45ebfe38 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwNzQ0NzE3LCJpYXQiOjE3NzA3NDQ0MTcsImp0aSI6ImY4NTllYjBhODRiODQ1YWRhNjUxMDUyNmI3YzgyNjIyIiwidXNlcl9pZCI6IjEifQ.XJN7ewSYACPyHWijxJy_oXNJ2BZ3Z0mVXZ0bjFD5Udw

###

POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwNzQ1OTU2LCJpYXQiOjE3NzA3NDU2NTYsImp0aSI6IjE2ZmViM2UyNDk5YjRlNzU5ZWY2YTI3YmEyYTQ2NTdmIiwidXNlcl9pZCI6IjEifQ.PqmJSJpTS-GHbyGsBkTUt-hMObSdXO98Ky0T7Iq4UaM

{
    "status": "Confirmed",
    "items": [
        {
            "product": 2,
            "quantity": 2
        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}

###

GET http://localhost:8000/orders/32d5c3cb-52ac-4b43-868c-faa1d4025dd2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwNzQ1OTU2LCJpYXQiOjE3NzA3NDU2NTYsImp0aSI6IjE2ZmViM2UyNDk5YjRlNzU5ZWY2YTI3YmEyYTQ2NTdmIiwidXNlcl9pZCI6IjEifQ.PqmJSJpTS-GHbyGsBkTUt-hMObSdXO98Ky0T7Iq4UaM

###

PUT http://localhost:8000/orders/32d5c3cb-52ac-4b43-868c-faa1d4025dd2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwNzQ1OTU2LCJpYXQiOjE3NzA3NDU2NTYsImp0aSI6IjE2ZmViM2UyNDk5YjRlNzU5ZWY2YTI3YmEyYTQ2NTdmIiwidXNlcl9pZCI6IjEifQ.PqmJSJpTS-GHbyGsBkTUt-hMObSdXO98Ky0T7Iq4UaM

{
    "status": "Pending",
    "items": [
        {
            "product": 2,
            "quantity": 3
        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}

###

DELETE http://localhost:8000/orders/32d5c3cb-52ac-4b43-868c-faa1d4025dd2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwNzQ2Mjc1LCJpYXQiOjE3NzA3NDU5NzUsImp0aSI6ImUyZTU2NzhlZTg1NzQxMGU5MWEzZGNlNzY4MmM1MDE0IiwidXNlcl9pZCI6IjEifQ.QnSAO_OhejsfpVTr9lj2UD8uVNu22vE0_Tdnbm-6TXU
