from rest_framework import serializers
from .models import Product, Order, OrderItem

# serializers.py: DRF serializer katmani.
# API request/response payload'larini Python objelerine cevirir.


# Product modeli icin serializer; create/update/list islemlerinde kullanilir.
class ProductSerializer(serializers.ModelSerializer):
    class Meta:
        # model: hangi Django modelini serialize ediyoruz.
        model = Product
        # fields: JSON cikisinda gorunecek alanlar.
        # ID DB tarafinda uretildigi icin istege bagli olarak eklenmez.
        fields = (
            'description', #you can't have the ID in the serializer if you're sending a POST request because the ID is generated by the database.
            'name',
            'price',
            'stock',
        )

    # validate_<field>: tek alan icin validation hook'u.
    def validate_price(self, value):
        if value <= 0:
            raise serializers.ValidationError(
                "Price must be greater than 0."
            )
        return value


# OrderItem serializer: order icindeki her satiri (urun+adet) temsil eder.
class OrderItemSerializer(serializers.ModelSerializer):
    # product = ProductSerializer() #OrderItem -> Product iliskisi tek obje oldugu icin many=True kullanilmaz.
    # Yukaridaki gibi yazarsak butun fieldlar yazilir ('name', 'description' ,'price', 'stock',)
    # Sadece belirli fieldlar yazilsin istiyorsak;
    # source=... ile ilgili Product alanlarini dogrudan okuruz.
    product_name = serializers.CharField(source='product.name') 
    product_price = serializers.DecimalField(max_digits=10, decimal_places=2, source='product.price')
    class Meta:
        model = OrderItem
        fields = (
            'product_name',
            'product_price', #belirli field degil de hepsini yazsaydik sadece 'prodcut' ve 'quantity' yeterliydi.
            'quantity',
            'item_subtotal'
        )


# Order serializer: order + nested items + hesaplanan toplam fiyat.
class OrderSerializer(serializers.ModelSerializer):
    # items: related_name='items' uzerinden nested serializer.
    items = OrderItemSerializer(many=True, read_only=True)  #Nested serializer making
    # total_price: hesaplanan alan; SerializerMethodField ile doldurulur.
    total_price = serializers.SerializerMethodField(method_name='total')  #SerializerMethodField

    # total(): total_price icin hesaplama fonksiyonu.
    # SerializerMethodField icin get_<field_adi> ismi veya method_name kullanilir.
    def total(self, obj):  #SerializerMethodField'a ait fonksiyon. (SerializerMethodField icin get_<field_adi> isimli bir metot aranir, yada method_name parametresi ile belirlenir.)
        order_items = obj.items.all()  #we use related name 'items' here.
        return sum(order_item.item_subtotal for order_item in order_items)  #models.py item_subtotal function

    class Meta:
        model = Order
        fields = (
            'order_id',
            'created_at',
            'user',
            'status',
            'items',   #Adding the nested serializer into fields
            'total_price'
        )


# Custom/standart olmayan response icin plain Serializer.
class ProductInfoSerializer(serializers.Serializer):  #generic / plain (normal) Serializer
    # get all products, count of products, max price
    products = ProductSerializer(many=True)
    count = serializers.IntegerField()
    max_price = serializers.FloatField()


# =====================================================
# Serializer vs ModelSerializer (Ozet Tablo)
# =====================================================

# Ozellik            | Serializer                  | ModelSerializer
# ------------------ | --------------------------- | ------------------------------
# Modele bagli mi?   | Hayir                       | Evet
# Field tanimi       | Manuel                      | Otomatik (modelden)
# CRUD uyumu         | Zayif                       | Guclu
# create / update    | Manuel                      | Otomatik
# Validation         | Manuel                      | Otomatik
# Model disi veri    | Evet                        | Hayir
# Esneklik           | Yuksek                      | Orta
# Kod miktari        | Fazla                       | Az
# Bakim kolayligi    | Dusuk                       | Yuksek
# Kullanim alani     | Ozet / Istatistik / Custom  | Standart REST API
# =====================================================
